
const app = {
  state: {
    settingListDate:[
      {
        name:'我的主页',
        icon:'el-icon-plus',
        path:'/settings/myHomepage'
      },
      {
        name:'收藏的文章',
        icon:'el-icon-plus',
        path:'/settings/collageArticle'
      },
      {
        name:'喜欢的文章',
        icon:'el-icon-plus',
        path:'/settings/favoriteArticles'
      },
      {
        name:'已购内容',
        icon:'el-icon-plus',
        path:'/settings/boughtContent'
      },
      {
        name:'我的钱包',
        icon:'el-icon-plus',
        path:'/settings/myWallet'
      },
      {
        name:'设置',
        icon:'el-icon-plus',
        path:'/settings/systemSettings'
      },
      {
        name:'帮助与反馈',
        icon:'el-icon-plus',
        path:'/settings/helpFeedback'
      },
      {
        name:'退出',
        icon:'el-icon-plus',
        path:'logout'
      },
    ],
    messageListDate:[
      {
        name:'评论',
        icon:'el-icon-plus',
        path:'/message/comment'
      },
      {
        name:'简信',
        icon:'el-icon-plus',
        path:'/message/janeLetter'
      },
      {
        name:'投稿请求',
        icon:'el-icon-plus',
        path:'/message/contributeRequest'
      },
      {
        name:'喜欢和赞',
        icon:'el-icon-plus',
        path:'/message/enjoyPraise'
      },
      {
        name:'关注',
        icon:'el-icon-plus',
        path:'/message/attention'
      },
      {
        name:'赞赏和付费',
        icon:'el-icon-plus',
        path:'/message/praisePay'
      },
      {
        name:'其他提醒',
        icon:'el-icon-plus',
        path:'/message/otherRemind'
      }
    ],
    systemSettingListDate:[
      {
        name:'基础设置',
        icon:'el-icon-plus',
        path:'/settings/systemSettings/baseSettings'
      },
      {
        name:'个人资料',
        icon:'el-icon-plus',
        path:'/settings/systemSettings/userSettings'
      },
      {
        name:'黑名单',
        icon:'el-icon-plus',
        path:'/settings/systemSettings/blackSettings'
      },
      {
        name:'赞赏设置',
        icon:'el-icon-plus',
        path:'/settings/systemSettings/praiseSettings'
      },
      {
        name:'账号管理',
        icon:'el-icon-plus',
        path:'/settings/systemSettings/accountSettings'
      }
    ]
  },
  mutations: {

  },
  actions: {

  }
}

export default app
